// Auto-Generated Plot Manifest (Strict Curation)
// Generated by Antigravity Data Storyteller
// Only includes explicitly tagged analytical outputs

window.plotsManifest = [
    {
        "category": "Actionable Insights",
        "folder": "actionable_insights",
        "description": "High-priority findings requiring immediate operational attention.",
        "context": {
            "what": "Critical efficiency gaps and service anomalies.",
            "why": "Direct input for immediate district-level intervention.",
            "when": "Review Daily"
        },
        "plots": [
            {
                "id": "insight_01",
                "title": "Critical Child Gap Regions",
                "path": "assets/curated_plots/01_worst_child_gaps.png",
                "featured": true,
                "desc": "Districts with >20% deficit in child biometric updates requiring immediate targeted camps."
            },
            {
                "id": "insight_02",
                "title": "Child Gap Trend Analysis",
                "path": "assets/curated_plots/02_child_gap_trend.png",
                "desc": "Worrying trend of widening child update gaps over the last 3 quarters."
            }
        ]
    },
    {
        "category": "System Baseline",
        "folder": "aadhaar_plots_final",
        "description": "Foundational metrics regarding system composition and flow.",
        "context": {
            "what": "Macro-level health and volume indicators.",
            "why": "Baseline for establishing 'normal' system behavior.",
            "when": "Monthly Review"
        },
        "plots": [
            { "id": "base_01", "title": "Pareto Volume Distribution", "path": "assets/curated_plots/01_pareto_lorenz.png", "featured": true, "desc": "Top 20% of districts drive 80% of total system volume, indicating high centralization." },
            { "id": "base_02", "title": "Bio-Demo Correlation", "path": "assets/curated_plots/02_biometric_demographic_correlation.png", "desc": "Strong positive correlation between demographic and biometric update volumes." },
            { "id": "base_03", "title": "Composition Over Time", "path": "assets/curated_plots/03_composition_over_time.png", "desc": "Structural shift from enrolment-heavy to update-heavy ecosystem is confirmed." },
            { "id": "base_04", "title": "Top Intensity Districts", "path": "assets/curated_plots/04_top_intensity_districts.png", "desc": "Urban centers showing sustained peak operational intensity throughout the year." },
            { "id": "base_05", "title": "Bottom Intensity Districts", "path": "assets/curated_plots/05_bottom_intensity_districts.png", "desc": "Districts with surprisingly low activity despite population density." },
            { "id": "base_06", "title": "State Week Heatmap", "path": "assets/curated_plots/06_state_week_heatmap.png", "desc": "Temporal efficiency heatmap showing state-level weekly throughput." },
            { "id": "ts_01", "title": "National Timeseries (Fixed)", "path": "assets/curated_plots/modified_01_national_timeseries_FIXED.png", "desc": "Corrected view of national daily throughput with outlier smoothing." },
            { "id": "ts_03", "title": "District Intensity (Consistent)", "path": "assets/curated_plots/modified_03_district_intensity_CONSISTENT.png", "desc": "Standardized intensity metric allowing cross-district comparison." },
            { "id": "ts_08", "title": "Age Disaggregation", "path": "assets/curated_plots/modified_08_age_disaggregated_ENHANCED.png", "desc": "Breakdown of service requests by age band." }
        ]
    },
    {
        "category": "Biometric Intelligence",
        "folder": "biometric_analysis",
        "description": "Deep dive into biometric update patterns and clustering.",
        "context": {
            "what": "Analysis of mandatory and voluntary biometric refreshes.",
            "why": "Key for maintaining registry uniqueness and fraud prevention.",
            "when": "Weekly System Health"
        },
        "plots": [
            { "id": "bio_05", "title": "Concentration Analysis", "path": "assets/curated_plots/05_concentration.png", "featured": true, "desc": "Gini coefficient analysis showing high concentration of biometric services." },
            { "id": "bio_06", "title": "Biometric Operational Clusters", "path": "assets/curated_plots/06_clusters.png", "desc": "Distinct operational signatures separating metro vs rural update behaviors." },
            { "id": "bio_07", "title": "Top Biometric Districts", "path": "assets/curated_plots/07_top_districts.png", "desc": "Leaderboard of districts with highest biometric refresh velocity." },
            { "id": "bio_13", "title": "Weekend vs Weekday", "path": "assets/curated_plots/13_weekend_weekday_comparison.png", "desc": "Significant drop in activity on weekends suggesting strong office-hour dependency." }
        ]
    },
    {
        "category": "Demographics & Equity",
        "folder": "demographic_analysis",
        "description": "Analysis of age, gender, and inclusivity metrics.",
        "context": {
            "what": "Assessment of service reach across population segments.",
            "why": "Ensures no demographic group is systematically excluded.",
            "when": "Quarterly Equity Audit"
        },
        "plots": [
            { "id": "demo_10", "title": "Minor Update Hubs", "path": "assets/curated_plots/core_10_top_districts_minor.png", "featured": true, "desc": "Districts with highest proportion of updates for <18 age group." },
            { "id": "demo_11", "title": "Volatility Hotspots", "path": "assets/curated_plots/core_11_volatile_districts.png", "desc": "Regions exhibiting highly erratic demographic update patterns." },
            { "id": "hi_03", "title": "Weekend Gini Scatter", "path": "assets/curated_plots/high_impact_03_weekend_gini_scatter.png", "desc": "Correlation between weekend service availability and inequality." },
            { "id": "hi_05", "title": "MoM Growth Heatmap", "path": "assets/curated_plots/high_impact_05_mom_growth_heatmap.png", "desc": "Month-over-Month growth rates visualizing regional acceleration." },
            { "id": "hi_06", "title": "Service Lorenz Curves", "path": "assets/curated_plots/high_impact_06_lorenz_curves.png", "desc": "Cumulative distribution showing moderate inequality in service access." },
            { "id": "hi_07", "title": "Spike Detection", "path": "assets/curated_plots/high_impact_07_spike_detection.png", "desc": "Automated detection of sudden anomalous surges in requests." },
            { "id": "core_02", "title": "Monthly Minor Share", "path": "assets/curated_plots/core_02_monthly_minor_share.png", "desc": "Seasonal fluctuations in minor updates correlated with school cycles." },
            { "id": "core_03", "title": "State-Month Heatmap", "path": "assets/curated_plots/core_03_state_month_heatmap.png", "desc": "State-level seasonality across the fiscal year." }
        ]
    },
    {
        "category": "Enrolment & Child Focus",
        "folder": "enrolment_analysis",
        "description": "Tracking new entrants and child enrolment efficiency.",
        "context": {
            "what": "Performance of child enrolment drives.",
            "why": "Critical for closing the gap in <5 and 5-18 age bands.",
            "when": "Campaign Review"
        },
        "plots": [
            { "id": "enr_07", "title": "Child Enrolment Leaders", "path": "assets/curated_plots/core_07_top_districts_child_share.png", "featured": true, "desc": "Districts successfully driving new child enrolments." },
            { "id": "enr_08", "title": "Enrolment Volatility", "path": "assets/curated_plots/core_08_volatility.png", "desc": "Stability analysis of new enrolment centers." },
            { "id": "hi_11", "title": "Child Share Acceleration", "path": "assets/curated_plots/high_impact_11_child_share_acceleration.png", "desc": "Rate of change analysis showing accelerating vs decelerating regions." },
            { "id": "hi_10", "title": "Gini vs Child Share", "path": "assets/curated_plots/high_impact_10_gini_child_share.png", "desc": "Does higher inequality lead to lower child coverage?" },
            { "id": "hi_13", "title": "Campaign Intensity", "path": "assets/curated_plots/high_impact_13_campaign_intensity.png", "desc": "Visible correlation between scheduled camps and enrolment spikes." },
            { "id": "hi_14", "title": "Cohort Trajectories", "path": "assets/curated_plots/high_impact_14_cohort_trajectories.png", "desc": "Longitudinal view of specific age cohorts entering the system." }
        ]
    },
    {
        "category": "Geospatial Intelligence",
        "folder": "geospatial_plots",
        "description": "Spatial patterns and regional inequality maps.",
        "context": {
            "what": "Geographic visualization of service deficits.",
            "why": "Essential for logistics and center placement.",
            "when": "Logistics Planning"
        },
        "plots": [
            { "id": "geo_02", "title": "Child Gap Map", "path": "assets/curated_plots/02_child_gap_map.png", "featured": true, "desc": "Geographic clustering of child service deficits across the north-east belt." },
            { "id": "geo_08", "title": "Seasonal Patterns", "path": "assets/curated_plots/08_seasonal_patterns.png", "desc": "Mapping the impact of harvest/monsoon seasons on operations." },
            { "id": "geo_10", "title": "Lorenz Inequality Map", "path": "assets/curated_plots/10_lorenz_curve_inequality.png", "desc": "Geospatial view of service distribution efficiency." },
            { "id": "geo_11", "title": "Gini Coefficient Analysis", "path": "assets/curated_plots/11_gini_coefficient_analysis.png", "desc": "Statistical inequality metrics by state." },
            { "id": "geo_12", "title": "Intra-State Heterogeneity", "path": "assets/curated_plots/12_within_state_heterogeneity.png", "desc": "High variance within states indicating uneven last-mile delivery." }
        ]
    },
    {
        "category": "Forecast & Trends",
        "folder": "forecast_final",
        "description": "Predictive modeling and decline analysis.",
        "context": {
            "what": "Future volume projections and risk zones.",
            "why": "Proactive resource planning.",
            "when": "Quarterly Strategy"
        },
        "plots": [
            { "id": "fc_01", "title": "Decline vs Volume", "path": "assets/curated_plots/01_decline_vs_volume_scatter.png", "desc": "Identifying high-volume districts entering a decline phase." },
            { "id": "fc_02", "title": "State Decline Summary", "path": "assets/curated_plots/02_state_decline_summary.png", "desc": "State-level aggregation of negative growth trends." },
            { "id": "fc_03", "title": "Enrolment-Update Correlation", "path": "assets/curated_plots/03_enrolment_update_correlation.png", "desc": "Correlation strength between new enrolments and subsequent updates." }
        ]
    },
    {
        "category": "Integrated & Special Reports",
        "folder": "integrated_analysis",
        "description": "Cross-domain correlations and special topics.",
        "context": {
            "what": "Complex multi-variable relationships.",
            "why": "Uncovers hidden systemic drivers.",
            "when": "Ad-Hoc Deep Dive"
        },
        "plots": [
            { "id": "int_01", "title": "Demo vs Bio Trends", "path": "assets/curated_plots/core_01_demo_vs_bio_monthly.png", "featured": true, "desc": "Comparative analysis of the two primary service arms." },
            { "id": "int_08", "title": "Demographic Intensity Heatmap", "path": "assets/curated_plots/core_08_demo_intensity_heatmap.png", "desc": "Heatmap of demographic update frequency per capita." },
            { "id": "int_06", "title": "Minor Share Scatter", "path": "assets/curated_plots/core_06_minor_share_scatter.png", "desc": "Correlation analysis of minor vs adult update patterns." },
            { "id": "int_07", "title": "Unified District Clusters", "path": "assets/curated_plots/core_07_district_clusters.png", "desc": "Holistic district segmentation based on all signals." },
            { "id": "spec_01", "title": "System Shift Ratio", "path": "assets/curated_plots/01_system_shift_ratio.png", "desc": "Quantifying the transition from growth to maintenance." },
            { "id": "spec_02", "title": "Invisible Economy (Weekend)", "path": "assets/curated_plots/02_invisible_economy_weekend_patterns.png", "desc": "Weekend activity patterns revealing informal sector access." },
            { "id": "spec_04", "title": "Healthcare Deserts", "path": "assets/curated_plots/04_healthcare_deserts_infant_gaps.png", "desc": "Correlation between healthcare access and infant enrolment." },
            { "id": "spec_bonus", "title": "Bonus: Child Attention Gap", "path": "assets/curated_plots/bonus_child_attention_gap.png", "desc": "Special analysis of the child attention gap metric." }
        ]
    }
];
